### ISSUE TITLE
bug?: Junos devices cannot resolve using resolver.rubykaigi.net

### ISSUE THREAD

**Issue by sorah** [ruby-no-kai/rubykaigi-net#103]

**Comment by hanazuki** [comment]
![image](https://github.com/ruby-no-kai/rubykaigi-net/assets/1135690/6649406a-b0f2-41ee-98d6-3015f9496e2e)

うちでは問題なさそうにみえる（こういうことではないのかな？）

**Comment by sorah** [comment]
cs-01からも同様にしてかえってこないんだよな

**Comment by hanazuki** [comment]
cs-01はアドレスまちがってそう
![image](https://github.com/ruby-no-kai/rubykaigi-net/assets/1135690/8f05efa4-9f28-42b4-a31e-69aa90bad38d)

**Comment by sorah** [comment]
🙇🏻‍♀️
