### ISSUE TITLE
スチールラック

### ISSUE THREAD

**Issue by sorah** [ruby-no-kai/rubykaigi-net#93]
[【ポール径25mm】ルミナス レギュラー スチールラック 3段 幅76 幅76×奥行46×高さ95\.5cm NLH7690\-3\| スチールラック・メタル製ラック通販のルミナスクラブ](https://www.luminous-club.com/products/detail/product_919/)

このへん？

**Comment by hanazuki** [comment]
よさそうなサイズ感

**Comment by sorah** [comment]
- ONU, tun (IX) x2
- nat x4
- EX x2

棚板3つでたりるか?

**Comment by sorah** [comment]
WLCがいるから4枚はあったほうが安心か

**Comment by hanazuki** [comment]
買われて届いてた．あとは開けてみてのお楽しみ
