### ISSUE TITLE
bug: etherip-ipsec か IPv6 の MTU/MSS がおかしい

### ISSUE THREAD

**Issue by sorah** [ruby-no-kai/rubykaigi-net#98]
IPv6 での iperf3 が性能出なくてクライアント側の MTU を下げたら解消したのでなんかおかしい

**Comment by sorah** [comment]
mss 1330 で改善した。何か計算ミスったか?

**Comment by hanazuki** [comment]
![image](https://github.com/ruby-no-kai/rubykaigi-net/assets/1135690/b7aba2ea-25dc-4799-9f67-cd8916c03847)

たぶんこう？

**Comment by hanazuki** [comment]
幸いNAT-Tをしてもかわらないらしい
![image](https://github.com/ruby-no-kai/rubykaigi-net/assets/1135690/c0c3548d-54f9-4708-ab3e-0ebf57485c7b)

**Comment by sorah** [comment]
padの最大長の認識ミスってたどころではないくらいズレていたが何が抜けていたのかは分からない(再計算したらほぼ同じになった)

**Comment by sorah** [comment]
1390 でトンネル絡むインタフェースに mtu 設定して回った

**Comment by sorah** [comment]
@hanazuki 対向でも設定必要かもしれません

**Comment by hanazuki** [comment]
わがやでもmtu設定してみた
